name: DevBox as a Service CI

permissions:
  id-token: write

# Trigger the workflow manually or on push to specific branches
on:
  workflow_dispatch: # Manually trigger the workflow
  pull_request: # Trigger the workflow on pull requests
    branches:
      - 'feature/**' # Branches containing feature/ in the name
      - 'bugfix/**' # Branches containing bugfix/ in the name
      - 'hotfix/**' # Branches containing hotfix/ in the name
      - 'release/**' # Branches containing release/ in the name
      - 'refactor/**' # Branches containing refactor/ in the name
      - 'test/**' # Branches containing test/ in the name
      - 'techdebt/**' # Branches containing techdebt/ in the name
  push:
    branches:
      - 'feature/**' # Branches containing feature/ in the name
      - 'bugfix/**' # Branches containing bugfix/ in the name
      - 'hotfix/**' # Branches containing hotfix/ in the name
      - 'release/**' # Branches containing release/ in the name
      - 'refactor/**' # Branches containing refactor/ in the name
      - 'test/**' # Branches containing test/ in the name
      - 'techdebt/**' # Branches containing techdebt/ in the name
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Update packages and upgrade Bicep
      - name: Update Packages and Upgrade Bicep
        run: |
          sudo apt-get update && \
          sudo apt-get upgrade -y && \
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
          sudo az bicep upgrade
      
      # Checkout the repository to get the source code
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Build the Bicep files for Dev Box Resources
      - name: Build Dev Box Bicep files
        run: az bicep build --file ./deploy/deploy.bicep --outfile ./bicepArtifacts/deploy.json

      # Compress the built Bicep artifacts into a zip file
      - name: Compress Bicep Artifacts
        run: |
          zip -r bicepArtifacts_v1.0.0-deploy-${{ github.run_number }}.zip ./bicepArtifacts

      # Upload the compressed Bicep artifacts
      - name: Upload Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip
          path: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip